<?php
/**
 * Created by PhpStorm.
 * User: dkliukin
 * Date: 6/30/18
 * Time: 10:28 AM
 */?>
<div style="width: 100%; height: 6.5vw;background-color: #08558b; position: fixed; bottom: 0">
    <div class="footer">
        <div>
            <p class="copyright"> © dkliukin. All rights reserved.</p>
        </div>
        <div class="logo">
<!--            <div class="moreInfo">-->
<!--                <a  href="//www.facebook.com/dima.klyukin.9"><img class="fbimg" src="../../src/facebook-2-64.ico"></a>-->
<!--                <a  href="//www.linkedin.com/in/dmytro-kliukin-0666a2159/"><img class="linkedin" src="../../src/linkedin.ico"></a>-->
<!--                <a  href="//twitter.com/DimKerA"><img class="twitter" src="../../src/tw.ico"></a>-->
<!--            </div>-->
            <div>
                <img class="DK" src="../../src/DK.png">
            </div>

        </div>
        <div class="mailphone">
            <div class="email">
                <p class="emailText">dkliukin@student.unit.ua</p>
                <img class="emailPic" src="../../src/email.ico">
            </div>
            <div class="mobile">
                <p class="mobileText">+38 (095) 75 23 714</p>
                <img class="mobilePic" src="../../src/mobile.ico">
            </div>
        </div>
    </div>
</div>