<?php
/**
 * $_SESSOIN['Login'] - login of current user
 * If $_SESSION['Login'] = "" - no users logged in. Optional "";
 *
 * $_SESSION['register'] - if empty - user exist and cant create:
 * $_SESSION['register'] = 0 - User Already exist
 * $_SESSION['register'] = 1 - optional value
 * $_SESSION['register'] = 2 - user registration finished (All ok)
 *
 * $_SESSION['email'] - check if user put right email in field:
 * $_SESSION['email'] = 0 - Address cant be rigth. User mistake. Need re-enter email
 * $_SESSION['email'] = 1 - optional value. If user type right email this value doesn't change
 *
 * $_SESSION['password'] - check if password right:
 * $_SESSION['password'] = 0 - PASSWORD and CONFIRM PASSWORD do not match.
 * $_SESSION['password'] = -1 - Password has less than 8 symdols
 * $_SESSION['password'] = 1 - optional password value
 *
 * $_SESSION['LoginTry'] - if value equal 0 user first time enter login/password. If value equal 1 user already failed
 * login and re-enter log/pass. Optional 0;
 *
 * $userData['Login'] - user login
 * $userData['Password'] - user pass
 * $userData['Email'] - user Email
 * $userData['UserID'] - User ID
 * $userData['FirstName'] - User First name
 * $userData['LastName'] - User Last Name
 * $userData['Age'] - User Age
 * $userData['Admin status'] - user admin status - 0 no admin status 1 admin status
 */
?>

<div class="boxtop" id="header">
    <div class="mainpage" id="headerGaleryButton">
        <button class="buttonMain" id="galleryButton">Gallery</button>
    </div>
    <div id="time" class="time">

    </div>
    <?php
    if(!empty($_SESSION['Login'])){
        echo "<div class='logsign'><div class='profile'>
    <a href='/profile/action'><button id='profileBut' class='buttonProfile'>".$_SESSION['Login']."</button></a></div>";
        echo "<div class=\"logoutDiv\">
        <a href='/login/logout'><button class='buttonLogout'>Log out</button></a>
    </div></div>";
    }
    if(empty($_SESSION['Login'])){

        echo "<div class='logsign' id='LoginSignin'>
<div class='signinDiv'>
            <a href='/login/action'><button class='buttonSignin'>LOG IN</button></a> 
          </div>
          
          <div class='signupDiv'>
            <a href='/signup/action'><button class='buttonSignup'>SIGN UP</button></a>
          </div></div>";

    }

    ?>
</div>


