<div class="loginForm" id="loginPage">
    <div class="Logincenter">
        <form method="post">
        <table>
            <div class="loginTable">

            <tr>
                <td style="align-content: center">
                    <div class="field">
                        <input id="loginSign" class='inputlogin' placeholder="Login" type="text" name="login" value="" required>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="field">
    <!--                    <p>Password:</p>-->
                        <input class='inputlogin' placeholder="Password" id="passLog" type="password" name="passwd" value="" required>
                    </div>
                </td>
            </tr>
            <th colspan="2" style="text-align: center">
                <button class="Buttons" id="buttonLogin" type="button" value="send" disabled>Log In</button>
            </th>

            </div>
        </table>
            <div style="display: flex; justify-content: center;">
                <button class="ButtonForget" id="buttonForgetPass" type="button">Forget password?</button>
            </div>
        </form>
    </div>
    <div class="loginError" id="errorLog">
        <p id="tet" class='login' style='margin-top: -0vw'></p>
    </div>
</div>

