<?php
/**
 * Created by PhpStorm.
 * User: dkliukin
 * Date: 6/13/18
 * Time: 2:37 PM
 */
/**
 * $_SESSOIN['Login'] - login of current user
 * If $_SESSION['Login'] = "" - no users logged in. Optional "";
 *
 * $_SESSION['register'] - if empty - user exist and cant create:
 * $_SESSION['register'] = 0 - User Already exist
 * $_SESSION['register'] = 1 - optional value
 * $_SESSION['register'] = 2 - user registration finished (All ok)
 *
 * $_SESSION['email'] - check if user put right email in field:
 * $_SESSION['email'] = 0 - Address cant be rigth. User mistake. Need re-enter email
 * $_SESSION['email'] = 1 - optional value. If user type right email this value doesn't change
 *
 * $_SESSION['password'] - check if password right:
 * $_SESSION['password'] = 0 - PASSWORD and CONFIRM PASSWORD do not match.
 * $_SESSION['password'] = -1 - Password has less than 8 symdols
 * $_SESSION['password'] = 1 - optional password value
 *
 * $_SESSION['LoginTry'] - if value equal 0 user first time enter login/password. If value equal 1 user already failed
 * login and re-enter log/pass. Optional 0;
 *
 * $userData['Login'] - user login
 * $userData['Password'] - user pass
 * $userData['Email'] - user Email
 * $userData['UserID'] - User ID
 * $userData['FirstName'] - User First name
 * $userData['LastName'] - User Last Name
 * $userData['Age'] - User Age
 * $userData['Admin status'] - user admin status - 0 no admin status 1 admin status
 */

?>
<div class="divNewP">
    <button class="AddNewP" id="NewPictureButton">Add New Photo</button>
</div>
    <div class="setPhotos" id="gallery">
        <div id="Photos" class="Photos">
            <input id="NumOfPhotos" type="hidden" value="0">
        </div>
        <div style="text-align: center">
            <div class="bn">
                <button class="buttonNext" onclick="bNext()">Upload More</button>
            </div>
        </div>
        <div style="height: 10vw">
        </div>
    </div>
<div class="hahghsfhfsjdfjf" style="height: 10vw;">
</div>