<div class="recoverForm" id="recoverPassForm">
    <div class="Logincenter">
        <form method="post">
            <table>
                <div class="loginTable">

                    <tr>
                        <td style="align-content: center">
                            <div class="field">
                                <input id="newRecoveredPasswd" class='inputlogin' placeholder="New password" type="password" value="" required>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="field">
                                <!--                    <p>Password:</p>-->
                                <input class='inputlogin' placeholder="Repeat password" id="newRecoveredPasswdConfirm" type="password" value="" required>
                            </div>
                        </td>
                    </tr>
                    <th colspan="2" style="text-align: center">
                        <button class="Buttons" id="buttonRecover" type="button" value="send" disabled>Recover</button>
                    </th>

                </div>
            </table>
            <div class="loginError" id="errorRecovering">
                <p id="ErrorMessage" class='login' style='margin-top: -0vw'></p>
            </div>
        </form>
    </div>
</div>