<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 11.06.2018
 * Time: 18:03
 */
/**
 * $_SESSOIN['Login'] - login of current user
 * If $_SESSION['Login'] = "" - no users logged in. Optional "";
 *
 * $_SESSION['register'] - if empty - user exist and cant create:
 * $_SESSION['register'] = 0 - User Already exist
 * $_SESSION['register'] = 1 - optional value
 * $_SESSION['register'] = 2 - user registration finished (All ok)
 *
 * $_SESSION['email'] - check if user put right email in field:
 * $_SESSION['email'] = 0 - Address cant be rigth. User mistake. Need re-enter email
 * $_SESSION['email'] = 1 - optional value. If user type right email this value doesn't change
 *
 * $_SESSION['password'] - check if password right:
 * $_SESSION['password'] = 0 - PASSWORD and CONFIRM PASSWORD do not match.
 * $_SESSION['password'] = -1 - Password has less than 8 symdols
 * $_SESSION['password'] = 1 - optional password value
 *
 * $_SESSION['LoginTry'] - if value equal 0 user first time enter login/password. If value equal 1 user already failed
 * login and re-enter log/pass. Optional 0;
 *
 * $userData['Login'] - user login
 * $userData['Password'] - user pass
 * $userData['Email'] - user Email
 * $userData['UserID'] - User ID
 * $userData['FirstName'] - User First name
 * $userData['LastName'] - User Last Name
 * $userData['Age'] - User Age
 * $userData['Admin status'] - user admin status - 0 no admin status 1 admin status
 */
?>

<!--<h1 class="headerProfile">PROFILE</h1>-->

<!--//                        <button class="uploadImage" onclick="img()">Upload Image</button>-->
<?php
    $user = new Profile();
    $userData = $user->getUserData();
if ($userData['Notification']) {
    $check = "checked";
}else {
    $check = "";
}

        echo "<div class=\"profileUpdateForm\">
<div>
<form action='/profile/update' method='post' style='margin-left: 8vw'>

                <table >
                <h1 style='font-size: 2vw; margin-left: 2vw'>Update profile info</h1>
                <p style='font-size: 1.3vw'>Enter your old login or new login to update profile.</p>
                    <tr>
                        <td>
                        <p>Login:
                             <input class='inputf' style='width: 78%' type='text' name='Login' id='UpdateLogin' placeholder='".$userData['Login']."' value=''></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <p>Email:
                            <input class='inputf' style='width: 78%' type='text' name='Email' id='UpdateEmail' placeholder='".$userData['Email']."' value=''></p>
                        </td>
                    </tr> 
                    <tr>
                        <td>
                        <p>Name:
                            <input class='inputf' style='width: 78%' type='text' name='Name' placeholder='".$userData['FirstName']."' value=''></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <p>Last Name:
                            <input class='inputf' type='text' name='Surname' placeholder='".$userData['LastName']."' value=''></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <p>Age: 
                            <input class='inputf' style='width: 82%' type='text' name='Age' placeholder='".$userData['Age']."'></p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p>Notification:<input class='inputf' type='checkbox' name='Notification' value='Yes' ".$check."></p>
                        </td>
                    </tr>
                  </table>
                  <button id='Upd' style='margin-left: 20%' class='buttonUpdate' >Update</button>
              </form></div>";

?>
<div style="display: flex; flex-direction: row; align-items: flex-start; margin-top: 2vw;">
    <button class='buttonChange' onclick="buttonChange()">Change Password</button>
    <button class='buttonDelete' onclick="buttonDelete()">Delete account</button>
</div>
<div class="UpdateError" id="ErrorUpd">
    <p id="updErr" class='login' style='margin-top: -0vw'></p>
</div>
</div>



<!--</div>-->










<!--<p>Upload Image</p>-->
<!--<div style='margin: 0vw; position: absolute'>-->
<!--    <form action='/profile/uploadPicture' id='othdetphotoform' enctype='multipart/form-data' method='post'>-->
<!--        <p><input id='photoloader' style='background-color: white' type='file' name='photoloader' accept='image/*'>-->
<!--            <input type='submit' value='send'></p>-->
<!--    </form>-->
<!--</div>-->





