<div class="recoverForm" id="recoverPass">
    <div class="Logincenter">
    <form method="post">
        <table>
            <div class="">
                <tr>

                    <td style="align-content: center">
                        <div class="field">
                            <input id="loginForRecover" class='inputlogin' placeholder="Login" type="text" name="login" value="" required>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="field">
                            <input class='inputlogin' placeholder="Email" id="EmailForRecover" type="text" name="Email" value="" required>
                        </div>
                    </td>
                </tr>
                <th colspan="2" style="text-align: center">
                    <button class="buttonRecover" id="buttonRecovering" type="button" value="send" disabled>Send Email</button>
                </th>

            </div>
        </table>
        <div class="loginError" id="errorRecovering">
            <p id="ErrorMessage" class='login' style='margin-top: -0vw'></p>
        </div>
    </form>
    </div>
</div>